name: reset

on:
  push:
    branches: 
      - main

  workflow_dispatch: 

jobs:
  reset:
      environment: stage
      runs-on: ubuntu-latest
      steps:
        - name: Save ssh key
          run: |
            # Save the private SSH key to a file
            echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /tmp/id_rsa
            chmod 600 /tmp/id_rsa

        - name: Ensure SSH directory exists
          run: mkdir -p ~/.ssh

        - name: Add SSH Host to Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
        - name: Test SSH Connection
          run: ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"

        - name: add another ssh
          run: ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo '${{secrets.NEW_SSH}}' >> ~/.ssh/authorized_keys" 